import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiNestjs,
  SiPhp,
  SiLaravel,
  SiPython,
  SiFastapi,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiGit,
  SiGithub,
  SiGitlab,
  SiDocker,
  SiNginx,
  SiApache,
  SiPostman,
  SiFigma,
  SiAngular,
  SiVuedotjs,
  SiNextdotjs,
  SiBootstrap,
  SiOpenjdk,
  SiSpring,
  SiSpringboot,
  SiFlask,
  SiGnubash,
  SiExpress,
  SiFlutter,
  SiDocusaurus,
  SiMoodle,
  SiWordpress,
} from 'react-icons/si'
import type { IconType } from 'react-icons'

const iconMap: Record<string, IconType> = {
  react: SiReact,
  typescript: SiTypescript,
  javascript: SiJavascript,
  tailwind: SiTailwindcss,
  html: SiHtml5,
  css: SiCss,
  nodejs: SiNodedotjs,
  nestjs: SiNestjs,
  php: SiPhp,
  laravel: SiLaravel,
  python: SiPython,
  fastapi: SiFastapi,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  docker: SiDocker,
  nginx: SiNginx,
  apache: SiApache,
  postman: SiPostman,
  figma: SiFigma,
  angular: SiAngular,
  vue: SiVuedotjs,
  nextjs: SiNextdotjs,
  bootstrap: SiBootstrap,
  java: SiOpenjdk,
  spring: SiSpring,
  springboot: SiSpringboot,
  flask: SiFlask,
  bash: SiGnubash,
  express: SiExpress,
  flutter: SiFlutter,
  reactnative: SiReact,
  docusaurus: SiDocusaurus,
  moodle: SiMoodle,
  wordpress: SiWordpress,
}

interface SkillIconProps {
  name: string
  className?: string
}

export function SkillIcon({ name, className }: SkillIconProps) {
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon className={className} aria-hidden />
}
